### PR TITLE
Give actual image region instead of resized image region on cropject

### PR DESCRIPTION
**Pull request by Fs02**

### CODE REVIEW

**Comment by CrackerakiUA** [comment]
Hello, thank you for your work, can you explain a bit about your changes and provide an codepen to show them.

**Comment by Fs02** [comment]
this actually related to #63 , but now the value of cropject is on the real image scale(not the canvas/resized image scale). 

http://codepen.io/anon/pen/wMLxGP

Edit : i thought simply changing the source address of the ngImgCrop would work, but it's actually didn't works really well on that pen. but it's actually works well on my project.

**Comment by Fs02** [comment]
found the bug, it was caused by `area-init-size="{ w:cropper.cropWidth,h:cropper.cropHeight}"`.
http://codepen.io/anon/pen/OMewOz

**Comment by CrackerakiUA** [comment]
wouldn't it be better to keep both, like 8 variables in that object?

**Comment by Fs02** [comment]
maybe that's better cause probably i'll need that too, i'll submit another commit asap

**Comment by CrackerakiUA** [comment]
Great, thank you

**Comment by Fs02** [comment]
allright, now it store 8 variables
http://codepen.io/anon/pen/mVZGwG

**Comment by CrackerakiUA** [comment]
i don't see new commits on this PR

**Comment by Fs02** [comment]
there are one commit before my last comment https://github.com/Fs02/ngImgCropFullExtended/commit/83938dc02b0be31f16f11bf904d41d698efbe451

**Comment by CrackerakiUA** [comment]
great work

**Comment by Fs02** [comment]
Thanks

**Comment by rickerd** [comment]
Sorry to f*ck up. Im not a pro in JavaScript and Angular, but thanks for the fix

**Comment by CrackerakiUA** [comment]
@rickerd what happen? everything is cool on your work. He just added some things, after i added some things on it.

**Comment by rickerd** [comment]
Im not mad or something. Only i wanted to get it all right but i made a little boo boo i think.
Im working with the blockObject now and i have some question.
Is the chat working?

**Pull request merged**
