### PR TITLE
Add area-min-relative-size.

### PR DESCRIPTION
**Pull request by komachi**

### CODE REVIEW

**Comment by CrackerakiUA** [comment]
Can you give an example of this new feature? Codepen would be best.

**Comment by rickerd** [comment]
This is what i've read in the README

**area-min-relative-size**

Optional. Min. width/height of the crop area (in pixels) relative to original image width/height. Usable if you use result-image-size="'max'" and want to get image larger that specified limit.

**Comment by CrackerakiUA** [comment]
All cool, i saw that, can you create codepen with it?

**Comment by komachi** [comment]
Here it is http://codepen.io/komachi/pen/vLPWrV

**Pull request merged**
