### PR TITLE
Feature add x/y initialization of crop area

### PR DESCRIPTION
**Pull request by hoppantut**
I've implemented functionality that will let the user set the initial x/y coordinates of the crop area. I modelled this change after the _area-init-size_ commit so there might be more improvements/clarifications available here.

This is functionality that I originally expected the _area-coords_ parameter object to handle, but it seems like that object is never actually used for anything in the code.

Also I fixed a typo in the readme.

### CODE REVIEW

**Comment by CrackerakiUA** [comment]
Thank you for your work.

**Comment by hoppantut** [comment]
What dictates when a new version is released? I think some of the problems people are having when using bower vs downloading directly from github  (ie. #35) has to do with changes being committed after the release of 0.5.4 while the compile/unminified/ng-img-crop.js still reports the current version as 0.5.4.

This initially confused me as bower downloaded version 0.5.4 but it differed from the 0.5.4 version in the master branch.

**Comment by CrackerakiUA** [comment]
After i put a release your code will be there.

**Comment by hoppantut** [comment]
Which is fine and exactly what I'd expect. My comment was related to the usage of the same version number for versions of the code that are not the same.

For example, if I use bower to download version 0.5.4, my code will not be there (this is also true for all other commits since the release of 0.5.4) - and this is what I expect. Next if I clone or download the master branch of this repo it will still say that the version number is 0.5.4 but the actual code has changed.

The point I'm trying to make is that I think you should take a more active stance related to the version number. This would avoid some issues where people report that the downloaded bower version contain bugs, while the github version doesn't (ie. #35 [comment](https://github.com/CrackerakiUA/ngImgCropFullExtended/issues/35#issuecomment-165326927)). The simplest way to do this would be to update the version number every time you make a new commit or merge in a pull request. Another way could be to maintain a development branch that you merge into the master branch each time you make a new release (and you would also update the version number when merging the development branch into master).

Anyway, I appreciate that you've kept this fork alive and well and is just making a suggestion as to how I think the integration with ie. bower could function better.

**Comment by CrackerakiUA** [comment]
I haven't tested your code yet to make release, just viewed the changes you did. I am doing my best on checking PR's :)

**Pull request merged**
