### PR TITLE
Let directive use 100% width and the height it needs

### PR DESCRIPTION
**Pull request by einarstubhaug**
I needed the directive to set its own height (grow/shrink) dynamically. It was only supported either using 100% height (image becomes vertically centered) or using fixed height.

I introduced the concept 'canvasScalemode'. If set to 'fixed-height' (also the default), everything works as before. If set to 'full-width', the image uses the full width of its container, and sets its height to as much as it needs to maintain aspect ratio.

To do that, the canvas gets static positioning instead of relative in the CSS. And when calculating CanvasDimensions in cropHost.js, it does not have height restrictions if scale mode is "full-width".

A rather big pull request, but I guess a useful feature?

Einar

 If set to 'full-width' the directive uses all width available _/
                             /_ and the canvas expands in height as much as it need to maintain the aspect ratio _/
                             /_ if set to 'fixed-height', the directive is restricted by a parent element in height

### CODE REVIEW

**Comment by CrackerakiUA** [comment]
Interesting, do you have codepen with this working on it?

**Comment by rickerd** [comment]
@einarstubhaug can you submit a working codepen? Its rather interesting to see.

**Comment by CrackerakiUA** [comment]
Have any one tried this?

**Comment by einarstubhaug** [comment]
Hi guys, I've been away on vacation, but back in civilization now and here is a working codepen. I forked the "rectangle crop" codepen and removed the .cropArea and belonging css. I wrapped the directive into a div that is 300px wide, and the directive now scales canvas to 300px width and whatever height it needs. http://codepen.io/einarstubhaug/pen/ZOvBjg

**Comment by CrackerakiUA** [comment]
Looks really cool.

**Pull request merged**
