### PR TITLE
added cross origin anonymous per https://github.com/alexk111/ngImgCro…

### PR DESCRIPTION
**Pull request by francirp**
Fixes cross origin problem that was fixed in ngImgCrop here: https://github.com/alexk111/ngImgCrop/pull/13/files

@CrackerakiUA not sure how to update the minified js file as well?

### CODE REVIEW

**Comment by CrackerakiUA** [comment]
i will check it as soon as i can.

**Comment by CrackerakiUA** [comment]
The only thing you add is `newImage.crossOrigin = 'anonymous';` not sure if that do something, need to test. Which problem that fix?

**Comment by francirp** [comment]
@CrackerakiUA see this PR from ngImgCrop: https://github.com/alexk111/ngImgCrop/pull/13/files

It fixes Uncaught SecurityError when image is loaded from an external URL (from S3 for example)

**Comment by CrackerakiUA** [comment]
Pretty simple solution for an bug we had, i didn't want to believe it's that simple. That why i delay that much pull accept. Thanks allot.

**Comment by francirp** [comment]
@CrackerakiUA  looks like I missed something here:

https://github.com/alexk111/ngImgCrop/commit/d244d0164a7de62a34aad054ebb984b856a510ab

I'll submit a new PR to fix tomorrow.

**Comment by CrackerakiUA** [comment]
i see, checking if url of image has http, images could be located on ftp also, something like this: ftp://domain.com/awesomeImage.jpg. Not sure if there are any other protocol which can give image.

**Pull request merged**
