### PR TITLE
Fix create object url

### PR DESCRIPTION
**Pull request by angelortiz-dev**
Hello I also have this problem https://github.com/CrackerakiUA/ngImgCropFullExtended/issues/129, so I made this PR to fix the issue.

### CODE REVIEW

**Comment by CrackerakiUA** [comment]
Don't know what that change, but it looks cool :)
Can you explain in few words?

**Comment by angelortiz-dev** [comment]
Guys, this was a mistake, the window.URL is correct, and the way I fixed it is deprecated. Please revert this PR, I'm sorry, the problem I still have is with the signature in the blob passed in this function.

**Comment by CrackerakiUA** [comment]
Done.

**Comment by rickerd** [comment]
@aandresortiz where does the error occur? Can we / i help?

**Comment by angelortiz-dev** [comment]
hi @rickerd I am using this directive inside a uib-modal and I was passing the image file from ngFileUpload but when was processing the result image I got a bad signature error, I fixed my issue in my custom directive moving back from a directive that used bindToController to a simple $scope, don't know what exactly was wrong, but in one intent passing an imageUrl instead of the image file, the crop was very slow. There is no problem using $scope and the file image directly. Thanks anyway!

**Comment by CrackerakiUA** [comment]
If you don't need live view of cropping area somewhere, add blocking object. In that way you will get ALLOT better performance.
http://codepen.io/Crackeraki/pen/XmEdPx here you can see how it works.

**Pull request merged**
