### PR TITLE
Added area-init-size

### PR DESCRIPTION
**Pull request by rickerd**
Added area-init-size option to start with a standard size instead of 200x200

Also did some code rectification. Some things weren't nicely closed.

Removed a console.log that was firing always.

### CODE REVIEW

**Comment by CrackerakiUA** [comment]
Have you tested this code with all my codepens?

**Comment by rickerd** [comment]
How to test it in all codepens? I didn't change it that much.
And i tested it on my project. Because i need the init functionality.

**Comment by rickerd** [comment]
I tested your codepens with this url.
https://rawgit.com/rickerd/ngImgCropFullExtended/master/compile/unminified/ng-img-crop.js

It works, the circle isn't affected only the rectangle version is altered.
http://codepen.io/anon/pen/bEzvEP

**Comment by rickerd** [comment]
Thank you!
I would try to bring more features as time passes

**Pull request merged**
