### PR TITLE
Bugfix/square area out of bounds

### LINKED ISSUE #109: Square crop going out of bounds
Can reproduce here: http://codepen.io/Crackeraki/pen/XmEdPx

screen shot 2016-05-13 at 5 02 06 pm

Using an image that's landscape, If you square crop and extend from the bottom right node, the square will become taller than the canvas. It results in graphical issues and odd behaviour.

### PR DESCRIPTION
**Pull request by aouji**
Fixes #109

### CODE REVIEW

**Comment by rickerd** [comment]
👍🏻

**Comment by CrackerakiUA** [comment]
Have you tested all codepens with this?

**Comment by aouji** [comment]
I did not unfortunately, I just tested it using different crop areas in my own implementation.

**Comment by rickerd** [comment]
Maybe unit tests would be nice.
And JSlint

**Comment by CrackerakiUA** [comment]
yes, but who have time for this :)
i just tested all codepens, looks cool.

**Comment by rickerd** [comment]
I really dont know.
Im trying to test code on my work so maybe id i get the hang of it i can implement it.

I will implement JSlint to have a nicer syntax and a higher coding standard.

**Comment by CrackerakiUA** [comment]
I have 6 projects on my back, with around 12h coding per day. Higher coding standards is way off time :)

**Pull request merged**
