### PR TITLE
Enabling support for maximizing the render depending on the image size

### PR DESCRIPTION
**Pull request by thibserot**
Add option to maximize the dimension of the result-image

### CODE REVIEW

**Comment by thibserot** [comment]
I haven't updated the minified version of the css, as I'm not sure of the procedure

**Comment by CrackerakiUA** [comment]
Hey, thanks for your work. I will merge it tomorrow after i check it.

**Comment by CrackerakiUA** [comment]
How to use it?

**Comment by thibserot** [comment]
I've updated the README: You just need to specify max in the result-image-size attribute

**Comment by thibserot** [comment]
Can you please release the version with this fix? (0.4.7)

**Comment by CrackerakiUA** [comment]
I will build demo with it and then i will make the release

**Comment by CrackerakiUA** [comment]
Can you fork this codepen http://codepen.io/Crackeraki/pen/QjmNVM and add your functionality? add new codepen here so i can fix the original codepen.

**Comment by thibserot** [comment]
I've submitted a new PR with codepen and a fix on my change (I'm not sure why but the zoom = disappeared in this PR....)
Here is the link to the PR: https://github.com/CrackerakiUA/ngImgCropFullExtended/pull/32

And codepen is: http://codepen.io/anon/pen/pgvwJB (will have to wait for PR 32 to be merged on head first)

**Pull request merged**
