### PR TITLE
Not working for mobile device or IOS when using take photo portrait mode

### PR DESCRIPTION
**Pull request by midori0507**
I just make changes to crop-host.js and do gulp build, no idea about changes in builded file

### CODE REVIEW

**Comment by midori0507** [comment]
Working codepen
http://codepen.io/anon/pen/dMppem

**Comment by CrackerakiUA** [comment]
i see, i need to add those changes into classes. I will merge this as soon as i can.

**Comment by dharitdesai** [comment]
:+1: need this asap :)

**Comment by CrackerakiUA** [comment]
@dharitdesai if you need this asap, please fix all changes on the classes and make pr.

**Pull request merged**
