### PR TITLE
Make most scope attribute of the directive optional

### PR DESCRIPTION
**Pull request by thibserot**
This error popped up after upgradin to angular 1.4.8 (or 1.5.0):
https://code.angularjs.org/1.4.8/docs/error/$compile/nonassign

Making optional argument optional solve the issue

### CODE REVIEW

**Comment by CrackerakiUA** [comment]
this is already added, any way, thanks for your work.

**Comment by thibserot** [comment]
Which version will contains it? Because in 0.4.7 (which is the latest) it's not included...

**Comment by CrackerakiUA** [comment]
https://github.com/CrackerakiUA/ngImgCropFullExtended/blob/master/compile/unminified/ng-img-crop.js
Line 2654

**Comment by thibserot** [comment]
This maybe on master but it's not on the latest release version (0.4.7):
https://github.com/CrackerakiUA/ngImgCropFullExtended/blob/0.4.7/compile/unminified/ng-img-crop.js#L2654

**Comment by CrackerakiUA** [comment]
i will make new release in day or two, then it will be there for sure

**Comment by thibserot** [comment]
ok cool! thanks

**Pull request closed without merging**
